### PR TITLE
Feature/activity model

### PR DESCRIPTION
**Pull request by offline0-stack**
## Describe your changes
I’ve implemented an Activity model, which includes fields such as name, amount, unitOfMeasure, startTime, and endTime, with some being optional and others required. This should align with our database representation of activities. 

## Issue ticket number and link
Drop-15
https://tripleten-apiary.atlassian.net/jira/software/projects/DROP/boards/5?selectedIssue=DROP-15

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by MrSurge87** [comment]
I updated the activity.ts file for the activity model to have all the fields completed. This was already worked on by a previous cohort so I just finished what was already started. This should align with our database representation of activities.

**Comment by dani9401** [comment]
@MrSurge87 Hey! This looks great to me and even gives me a good fix for something I missed on my PR. Thanks for that!

The only fix needed here is that it looks like the PR is failing the linting process. This should be pretty easy to fix by running npm run lint to see errors, or npm run lint:fix to fix any errors.

**Comment by MrSurge87** [comment]
Thanks so much! I ran npm run lint:fix and I believe all the errors are gone now.

**Comment by dani9401** [comment]
> Thanks so much! I ran npm run lint:fix and I believe all the errors are gone now.

Hey! try running linting on ALL files that show up with linting errors (not just the files you worked on)

**Pull request closed without merging**
